# Preregistration {-}

## Roadmap {-}

- Read
    - [@Nosek2018-jk](http://dx.doi.org/10.1073/pnas.1708274114)
    - [@Ledgerwood2018-sn](http://dx.doi.org/10.1073/pnas.1812592115) or [@Goldin-Meadow2016-mc](https://www.psychologicalscience.org/observer/why-preregistration-makes-me-nervous)
    - (Optional) [@Claesen2021-ae](http://dx.doi.org/10.1098/rsos.211037)
- [Submit]{.orange_due}: [Exercise 04: Replication](#ex_replication)

## [@Nosek2018-jk](http://dx.doi.org/10.1073/pnas.1708274114) {-}

>*Abstract*
>
>Progress in science relies in part on generating hypotheses with existing observations and testing hypotheses with new observations. This distinction between postdiction and prediction is appreciated conceptually but is not respected in practice. Mistaking generation of postdictions with testing of predictions reduces the credibility of research findings. However, ordinary biases in human reasoning, such as hindsight bias, make it hard to avoid this mistake. An effective solution is to define the research questions and analysis plan before observing the research outcomes—a process called preregistration. Preregistration distinguishes analyses and outcomes that result from predictions from those that result from postdictions. A variety of practical strategies are available to make the best possible use of preregistration in circumstances that fall short of the ideal application, such as when the data are preexisting. Services are now available for preregistration across all disciplines, facilitating a rapid increase in the practice. Widespread adoption of preregistration will increase distinctiveness between hypothesis generation and hypothesis testing and will improve the credibility of research findings.
>-- [@Nosek2018-jk](http://dx.doi.org/10.1073/pnas.1708274114)

### Types {-}

- Preregistration (of analysis plans)
- Registered reports, [@Chambers_undated-ax](https://royalsociety.org/blog/2016/11/registered-reports-what-are-they-and-why-are-they-important/); [@Center_for_Open_Science_undated-yg](https://www.cos.io/initiatives/registered-reports)

### Commentary about {-}

- [@Ledgerwood2018-sn](http://dx.doi.org/10.1073/pnas.1812592115)

- [@Goldin-Meadow2016-mc](https://www.psychologicalscience.org/observer/why-preregistration-makes-me-nervous)

### Examples {-}

- [clinicaltrials.gov](https://clinicaltrials.gov/)
- [AsPredicted.org](https://aspredicted.org)

## Next time... {-}

- Data sharing
    - [@Houtkoop2018-tl](https://doi.org/10.1177/2515245917751886)
    - [@Tenopir2020-mq](http://dx.doi.org/10.1371/journal.pone.0229003)
